### ISSUE TITLE
Support Puppet 7

### ISSUE THREAD

**Issue by iainhallam** [EdgeJ/puppet-filepath#4]
Puppet 7 has been out for some time, but this module only supports <7, rather than <8. Is it possible to check whether there are any issues with upping the version constraint, please?

**Comment by EdgeJ** [comment]
Hi @iainhallam, sorry it's taken me awhile to see this. The notification got buried underneath a bunch of other stuff. This repo is pretty lightly maintained on my part because I haven't heavily used Puppet in a while (and to be frank, wasn't sure there were many others who pulled this downstream), so I've not updated the version constraints. I'll try to find some time in the next few weeks to check into what the differences are between versions greater than 6 and see if I can update accordingly.
